apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://{{ monitoring_ip }}:9090
    uid: prometheus
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://{{ monitoring_ip }}:3100
    uid: loki
