---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull Backend Image
  community.docker.docker_image:
    name: ghcr.io/himanm/devops-project-8/backend:latest
    source: pull

- name: Run Backend Container
  community.docker.docker_container:
    name: backend
    image: ghcr.io/himanm/devops-project-8/backend:latest
    state: started
    restart_policy: always
    ports:
      - "3001:3001"
    env:
      DB_HOST: "production_db" # Example env

- name: Run Node Exporter
  community.docker.docker_container:
    name: node-exporter
    image: prom/node-exporter:latest
    state: started
    restart_policy: always
    ports:
      - "9100:9100"

- name: Run cAdvisor
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    devices:
      - /dev/kmsg

- name: Copy Promtail Config
  template:
    src: promtail-config.yml
    dest: /tmp/promtail-config.yml

- name: Run Promtail
  community.docker.docker_container:
    name: promtail
    image: grafana/promtail:latest
    state: started
    restart_policy: always
    volumes:
      - /var/log:/var/log
      - /tmp/promtail-config.yml:/etc/promtail/config.yml
