---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Pull Backend Image
  community.docker.docker_image:
    name: ghcr.io/himanm/devops-project-8/backend:latest
    source: pull

- name: Run Backend Container
  community.docker.docker_container:
    name: backend
    image: ghcr.io/himanm/devops-project-8/backend:latest
    state: started
    restart_policy: always
    ports:
      - "3001:3001"
    env:
      DB_HOST: "production_db" # Example env
